### ISSUE TITLE
ビルドのキャンセル

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/NeoShowcase#196]
- キャンセルする場合
  - 明示的にキャンセルした時
- キャンセルするもの
  - [x] ビルドキュー
  - [ ] 実行中のビルド

**Comment by hijiki51** [comment]
返されたJobIDの扱い方については別で検討したほうが良い。
- そもそもqueueの中身は外から見えるべきなのか
- いま待機中のjob一覧をどこかで持たなければならないが、それはどこか
    - そうするとappbuildserviceに持たせることになるがその情報を取ってくるのに毎回appbuildserviceにとりに行くほうがいいのか、それともDBに情報として持つべきなのか


とりあえずこの問題については別で扱うことにする（返すだけ返して無視）
