### ISSUE TITLE
ユーザーのSignup機能

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/NeoShowcase#222]
OIDCのみ

**Comment by motoki317** [comment]
ref #241

**Comment by motoki317** [comment]
https://github.com/thomseddon/traefik-forward-auth とか

**Comment by motoki317** [comment]
> Connect headers are just HTTP headers

https://connect.build/docs/web/headers-and-trailers

らしいのでhttp middlewareが使える...？
