### ISSUE TITLE
環境変数を複数の粒度で提供するか考える

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/NeoShowcase#233]
- アプリケーション単位にしか持てないようにする
  - 環境変数のkeyを使い分けないといけないのbad practice感あるので避けたい
- ブランチ単位でしか持てないようにする
- `BranchEnvironment`と`ApplicationEnvironment`の両方を用意する
  - 一旦こっちで実装して`ApplicationEnvironment`の使用頻度が低かったら切る

要相談

**Comment by motoki317** [comment]
一旦デプロイ単位（`BranchEnvironment`）のみ提供の方向
