### ISSUE TITLE
旧showcase.yamlイメージビルド対応

### ISSUE THREAD

**Issue by wtks** [traPtitech/NeoShowcase#26]
+ 共通イメージを使用(`wtks/ns-base:20210110`(暫定))
+ イメージビルドでstartupのコマンドを実行
+ ビルドするイメージのentrypointをentrypointコマンドに設定

**Comment by wtks** [comment]
https://github.com/traPtitech/NeoShowcase/blob/a142f9e26375e1603bdaa192b05ce7a70ee20c5c/pkg/builder/task.go#L215
https://github.com/traPtitech/NeoShowcase/blob/a142f9e26375e1603bdaa192b05ce7a70ee20c5c/pkg/builder/task.go#L267

**Comment by wtks** [comment]
多分自動生成するDockerfileにentrypoint, startupコマンドを直接埋め込むより、それらのコマンドが書かれたシェルスクリプトをイメージにADDして、それをRUNやENTRYPOINTで指定するようにしたほうがいい

**Comment by hijiki51** [comment]
`TODO Dockerfileの検証`
これはDockerfileの何を検証すればいいのでしょうか

**Comment by wtks** [comment]
今の仮実装だとDockerfileにsprintfでentrypoint変数とかを何も考えずに埋め込んでるんですが、それだとentrypointコマンドに改行入れたりすると、通常のシェルのコマンドじゃなくてDockerfileのディレクティブとか埋め込めてやりたい放題出来てしまうので、そこらへんの問題が無いかどうかを検証したり、そもそもそういうことが起こらないような実装にするっていう話です。

まあそれが難しいので、https://github.com/traPtitech/NeoShowcase/issues/26#issuecomment-770154365 に書かれてるような実装に変えるのが楽かなって感じ
