### ISSUE TITLE
builderが特定のブランチ・タグをチェックアウトしてビルドできるようにする

### ISSUE THREAD

**Issue by wtks** [traPtitech/NeoShowcase#32]
https://github.com/traPtitech/NeoShowcase/blob/a142f9e26375e1603bdaa192b05ce7a70ee20c5c/api/proto/neoshowcase/services/builder/service.proto#L19
builderへのGRPCリクエストでブランチ・タグを指定できるようにパラメーターを追加

https://github.com/traPtitech/NeoShowcase/blob/a142f9e26375e1603bdaa192b05ce7a70ee20c5c/pkg/builder/task.go#L85
でブランチ・タグを指定してクローンできるようにする

**Comment by cskd8** [comment]
ブランチもタグもどっちもあった場合どうすればいいですか？

**Comment by sapphi-red** [comment]
ブランチもタグもコミットへの参照だから、どっちも同じパラメータで受け付ければよいと思う
https://git-scm.com/book/ja/v2/Git%E3%81%AE%E5%86%85%E5%81%B4-Git%E3%81%AE%E5%8F%82%E7%85%A7

**Comment by wtks** [comment]
↑そう
NeoShowcase側の実装も、branchとtagは同じフィールドやDBのカラムで扱っていいです

**Comment by sapphi-red** [comment]
ブランチ名の指定だと衝突するから`ref-type: 'branch' | 'tag'`と`ref`ですか？
`ref: refs/heads/～ | refs/tags/～`ですか？

**Comment by cskd8** [comment]
中身に"heads/hoge"とか"tags/hoge"がくるようなstringで持ってあげて、どちらの場合も同じようにrefに"refs/"+stringみたいに指定してCloneしてくればいいって感じですか？

**Comment by wtks** [comment]
それでお願いします
