### ISSUE TITLE
アプリを追加できるようにする

### ISSUE THREAD

**Issue by wtks** [traPtitech/NeoShowcase#36]

**Comment by FujishigeTemma** [comment]
https://wiki.trap.jp/SysAd/dev/NeoShowcase/Spec/API-Server#:~:text=%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%8D%E3%83%83%E3%83%88%E3%81%AB%E5%85%AC%E9%96%8B-,%E4%BA%8B%E5%89%8D%E3%81%AB%E7%99%BB%E9%8C%B2%E6%B8%88%E3%81%BF%E3%81%AE%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E4%BB%A5%E5%A4%96%E3%81%AF%E7%84%A1%E8%A6%96,-Attachments

**Comment by FujishigeTemma** [comment]
↑追記しました

**Comment by hijiki51** [comment]
仕様
https://md.trap.jp/RUSDLO0FRfywin-mk4Lreg?both

**Comment by hijiki51** [comment]
providersのnameですが、githubはともかくgiteaやgitlabはプロバイダじゃなくてサービスなので複数存在しますね。
なので、nameの部分をURLのドメインにして対応しようと思うのですがどうでしょうか？
