### ISSUE TITLE
ビルドキューを作る

### ISSUE THREAD

**Issue by wtks** [traPtitech/NeoShowcase#37]
空いてるbuilderが出来るまでビルドを待機させる

**Comment by wtks** [comment]
要件
+ builderは0個以上起動している
  + 0個の場合は1個以上起動するまで永遠にビルドがキューに待たされる
  + builderの数は動的に増減する
+ キューされたビルドはキャンセルできる

**Comment by hijiki51** [comment]
- builderの数は動的に増減する
↑に対応するための実装を考えているんですが、builderにキューの中身を取りに行かせるのと、appのほうでbuilderの状況を見て適宜渡すのとどちらがいいんでしょうか？

**Comment by wtks** [comment]
appで全ビルダーの状態を常に把握・制御したいので、appがbuilderに渡す方で

**Comment by wtks** [comment]
毎回ビルダーを立てているというよりかは、常に立ってるただ1つのビルダーにビルドタスクを渡しているだけ。そのビルダーがその時ビルド中だったらエラーでビルド失敗する。

リクエストごとにビルダーを立てるのではなくて、稼働中(appと接続中)のビルダーの中からWAITING状態になってるビルダーを選んで、そいつにビルドタスクを渡すという感じ。WAITING状態なビルダーが存在しなければ、そのビルドタスクはキューイングされて、WAITING状態なビルダーが出現するまで待つ

現状のコードではビルドキュー周りの実装何も無いです。

**Comment by hijiki51** [comment]
なるほど、では現在存在する`GetStatus`は常に立っているただ一つのビルダーの状況を返す感じで、複数のビルダーがたつ場合はそこも変更しないといけないという感じでいいでしょうか？

**Comment by wtks** [comment]
`GetStatus`はそのクライアントで繋がっている特定の1つのビルダーのステータスを返すものなので、そこを変更するわけではないです。`BuilderServiceClient`を複数持ってそれに対応するビルダーを管理するような機構の追加が必要ですね。

**Comment by wtks** [comment]
そもそも現状だとappmanagerが複数のビルダーを接続できるようにもなってないですね。
実はこのタスク結構大変だから分割したほうがいいな

**Comment by wtks** [comment]
現状で実装するとしたら実際に保持するのは１つのビルダーのみだけど、内部では複数のビルダーを扱えるような想定で実装をする感じかなあ

**Comment by hijiki51** [comment]
現在は`app_impl.go:293`あたりで直接builderの`StartBuild~`を叩いてレスポンスを取っているらしいのですが、キューを実装した場合、レスポンスはどのように返すべきですか？キューの実行が終わるまで待つことも考えましたがなんかちがうなあと思いまして…

**Comment by wtks** [comment]
`func (app *appImpl) RequestBuild`の返り値のこと？それならキューに追加できたらnilを返せばよいです。今もビルド終わるの待ってないですよ

**Comment by hijiki51** [comment]
あ、本当だ…勘違いしてました、すみません

**Comment by hijiki51** [comment]
ビルドキューの実装はひとまずできたのでテストをしたいのですが、どうすれば`RequestBuild`をたたけますかね？
