### ISSUE TITLE
BuilderService.CancelTaskを呼び出してもstatusがBUILDINGから変わらない

### ISSUE THREAD

**Issue by wtks** [traPtitech/NeoShowcase#44]
buildkitdのビルドは停止されるが、builderのステータスは変わらず、以降ビルドが出来なくなってしまう

**Comment by cskd8** [comment]
`pkg/builder/task.go`のL107でcontextが新しく作られていて、これを`ctx`に直したらCANCELEDになりました

**Comment by cskd8** [comment]
あまりわかってないですが`pkg/builder/task.go`の`buildImage`の`eg.Go`のGoroutineの途中でCancelが飛んできて、そのときに`eg.Wait`に`context.Canceled`のエラーが入ってから呼び出し元に変えるべきなのが呼び出し元も含めてCancel後の実行がすべて止まっていそうです(`pkg/builder/service.go`の131行目とかでプリントデバッグしても何も表示されない)

**Comment by wtks** [comment]
https://github.com/traPtitech/NeoShowcase/blob/d82955db6e6102748f47dbe4ef8076471cea6037/pkg/builder/task.go#L198
のgoroutineの返り値のerrがnilでない場合に、`close(ch)`でチャネル閉じたらちゃんと処理進む気がする。
https://github.com/traPtitech/NeoShowcase/blob/d82955db6e6102748f47dbe4ef8076471cea6037/pkg/builder/task.go#L291
こいつに渡してるchチャネルがcloseされないからこの関数から処理が返ってこない疑惑

**Comment by wtks** [comment]
https://github.com/traPtitech/NeoShowcase/blob/d82955db6e6102748f47dbe4ef8076471cea6037/pkg/builder/task.go#L273
が正常に終了する場合は、Solve関数の中でchがcloseされるので、その場合はchを二重にcloseしないように注意

**Comment by wtks** [comment]
chを二重にcloseするとpanicが発生します

**Comment by cskd8** [comment]
それ試して、できてそうだったらPR出します

**Comment by cskd8** [comment]
とりあえず、必ずキャンセル打つ前提で
https://github.com/traPtitech/NeoShowcase/blob/d82955db6e6102748f47dbe4ef8076471cea6037/pkg/builder/task.go#L291


のあとに`ch`をcloseするようにして試してみたら、キャンセルしてその後ほかのビルド回せるようにはなったんですけど、DBのresultがBUILDINGのままになっています

**Comment by wtks** [comment]
関係ないっぽい

**Comment by wtks** [comment]
調べたら、https://github.com/traPtitech/NeoShowcase/issues/44#issuecomment-783256596 に書かれてる関数はerrの有無に関わらず、引数に渡されたチャネルをcloseするので`ch`があーだこーだの話は全部関係ないですね・・・

**Comment by cskd8** [comment]
https://github.com/moby/buildkit/blob/master/examples/build-using-dockerfile/main.go

を真似して`progressui.DisplaySolveStatus()`の`ctx`を`context.TODO()`に変えたら、DBのresultが`CANCELED`ではなくて`FAILED`になる以外いい感じの挙動になりました

**Comment by wtks** [comment]
> `progressui.DisplaySolveStatus()`の`ctx`を`context.TODO()`に変えたら
これでいいので、あとはresultをCANCELEDにできればいいですね。

https://github.com/traPtitech/NeoShowcase/blob/02e1e4e5ca9bd8ec93beceb437e632e4033b1ae8/pkg/builder/service.go#L133
の判定の仕方が間違っているかもしれん

**Comment by cskd8** [comment]
あーそれですね、`err == context.Canceled`が`false`でした

**Comment by cskd8** [comment]
条件を`err.Error() == "failed to solve: rpc error: code = Canceled desc = context canceled" || err == context.DeadlineExceeded`にするとちゃんと`CANCELED`にはなったので、もう少しいい感じにできないか考えたら解決しそうです。

**Comment by wtks** [comment]
`err == context.Canceled || err == context.DeadlineExceeded`はそのままで、更にORで`errors.Is(status.FromContextError(context.Canceled))`繋げばいけそうなきがする
https://github.com/grpc/grpc-go/blob/26c143bd5f59344a4b8a1e491e0f5e18aa97abc7/status/status.go#L118

**Comment by cskd8** [comment]
いい感じですね
`errors.Is(err, status.FromContextError(context.Canceled).Err())`をORでつなげました
![image](https://user-images.githubusercontent.com/57042565/108717566-c5286080-7560-11eb-992e-44f9cc3a64e1.png)

**Comment by wtks** [comment]
yatta-

**Comment by cskd8** [comment]
通常のビルドも成功しています
ブランチ分けてPR出します

![image](https://user-images.githubusercontent.com/57042565/108717892-26e8ca80-7561-11eb-88f5-dc9517251c4c.png)
