### ISSUE TITLE
ビルド詳細画面

### ISSUE THREAD

**Issue by motoki317** [traPtitech/NeoShowcase#480]
- ビルドの詳細
- runningの場合はビルドのキャンセルボタン
- successでない、かつrunningでない場合は再ビルドボタン
- artifactが存在する場合はそれのダウンロードボタン

**Comment by detteiu8383** [comment]
これに取り組もうと思っているのですが、いくつか質問があります

1. > runningの場合はビルドのキャンセルボタン

   の"runninng"は、ApplicationのContainerStateがrunningである場合、の意味ですか?(BuildのbuildStatusがbuildingである場合の意...?)

3. > artifactが存在する場合はそれのダウンロードボタン

   artifactのDLボタンを、Actionsのカード内に再ビルドボタンなどと同列に表示するのか / 別のartifact詳細カードを作ってその中にボタンを置くのか、
といった部分はデザイン担当に投げて決めてもらうべきですか?それとも僕のほうで考えて作ってしまうべきですか?

**Comment by motoki317** [comment]
今はかなりひどい仮デザインで作ってあります(多分見てもらった通り)
その上で、確かもう少し実装する要素はあるろ思うのでそれを追加してもらえると助かります

1 → runningじゃなくてbuildingのとき、ですね
2 → デザインはないので自分でとりあえずいい感じに作ってもらっていいです(あまり時間を取りすぎず)

本デザインはもちろん相談ですが、担当(tarariraくん)の忙しさ次第

**Comment by motoki317** [comment]
キャンセルボタンとDLボタンが無いのかな
