### ISSUE TITLE
汎用ベースイメージの作成

### ISSUE THREAD

**Issue by wtks** [traPtitech/NeoShowcase#5]
+ 現行のshowcaseベースイメージみたいなのを作る
  + 現行のイメージはDockerfileがビルド出来なくなってます
+ `archlinux`ではなくて、`ubuntu` or `alpine`から作る 
+ イメージに含めるコンパイラや各種言語のパッケージマネージャ等は、現状稼働中のshowcaseアプリケーションが何を使っているか調査して決める？

**Comment by hijiki51** [comment]
数えてみた感じ、言語は
golang:46
node_js:67
python:7
rust:6
PHP:7
gawk:1

でした。
パッケージマネージャは
npm:46
yarn:12
go mod:18
dep:7
pip:4
pip3:1
cargo:4
pacman:9

でした。（showcase.yamlのstartupしか見てないので数え間違いや見落とし等あるかもしれません）
やっぱりBOTの影響が大きいですね…

**Comment by sapphi-red** [comment]
> pacman

これに関しては何を入れてるかまで確認したほうがよさそうですね(より上流のパッケージマネージャなので)

**Comment by hijiki51** [comment]
```
    "pacman -Syy --noconfirm lib32-gcc-libs": 4,
    "pacman -Syy --noconfirm xinetd": 5,
    "npm i && yes | pacman -Sy kakasi": 1,
    "pacman -Sy --noconfirm mariadb-clients;":1
    "yes | pacman -Sy rustup": 2,
    "pacman -Syy; pacman --noconfirm -S libsm libxrender libxext":1
    "pacman -Sy --noconfirm chromium": 1,
    "Include = /etc/pacman.d/mirrorlist\" >> /etc/pacman.conf": 1,
    "yes | pacman -Sy  xinetd gcc-multilib lib32-glibc": 1,
```
pacmanが使われてるのはこのあたりですね。(:の後は出現回数です)

**Comment by hijiki51** [comment]
確認なんですが、後方互換性は保証すべきですよね？

**Comment by hijiki51** [comment]
WIP:
イメージに使うコンパイラやマネージャは
- nodejs
    - yarn
    - npm
- go
- python,python2,python3
    - pip,pip3
- rust
    - cargo
