### ISSUE TITLE
environmentsテーブルにアプリの環境変数設定情報を追加する

### ISSUE THREAD

**Issue by wtks** [traPtitech/NeoShowcase#57]
NeoShowcaseアプリのコンテナには環境変数を渡せるようになっているが、何を渡すかの設定が保存されている場所は無いため、`environments`テーブルに`envvars`カラムを追加してそこにコンテナに設定する環境変数を保存しておけるようにする。

環境変数は複数設定できるが、データベースのカラムは`envvars`１つであるため、`envvars`には環境変数のキーとバリューを持ったオブジェクト(`map[string]string`)のjson文字列を格納するようにする。

**Comment by FujishigeTemma** [comment]
今ある`environments`テーブルを改名して、以下のカラムを持つ新`environments`を作る
- 旧`environments`テーブルのID
- 環境変数のキー
- 環境変数の値
