### ISSUE TITLE
アプリケーションのビルドに失敗したときの状態を分かりやすく表示したい

### ISSUE THREAD

**Issue by oribe1115** [traPtitech/NeoShowcase#598]
## バグの概要
アプリケーションのGeneralの画面で、ビルドに失敗したときも状態が`Deploying`として表示される

## 再現手順
1. 作成したアプリケーションでビルドを失敗させる(Buildsの最新ログがFailedになっていることを確認する)
2. Generalを開く
3. Overallのところで状態が`Deploying`となっている

### 期待する動作
`Build Failed`などといった、ビルドが失敗していることがわかる表示がされて欲しい

## スクリーンショット
![image](https://github.com/traPtitech/NeoShowcase/assets/50443000/ae4cbfba-5b0f-461e-9777-f0e9eff9f514)

**Comment by motoki317** [comment]
これは今のところ仕様です

**Comment by motoki317** [comment]
本デザイン策定と同時に検討中
