### ISSUE TITLE
[Feature]: ビルド時に環境変数を設定してほしい

### ISSUE THREAD

**Issue by ras0q** [traPtitech/NeoShowcase#630]
### 問題の説明

Next.jsのようにビルド時に環境変数を設定しないと動かない場合がある
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

### 新機能の説明

Runtime Command/Dockerfile でビルド時に環境変数を設定するようにしてほしい

**Comment by motoki317** [comment]
duplicate of #489
