### ISSUE TITLE
利用技術やアーキテクチャをまとめたドキュメント(design docs的なもの)が欲しい

### ISSUE THREAD

**Issue by kyosu-1** [traPtitech/NeoShowcase#697]
開発者向けに

**Comment by kyosu-1** [comment]
traQの方のwikiにも一部まとまっているので二重管理になってしまうかも

**Comment by motoki317** [comment]
二重管理になってしまうのはどちらかに書いたらそちらをリンクで参照すればいい

**Comment by kyosu-1** [comment]
traQのwiki側で作ったものは外部の人は見れないので、内部向けのもの以外のものは基本的にはこちらのリポジトリの方にまとめた方がとして良かったりしそうですかね。(traQのwiki側が参照する形で)
