### ISSUE TITLE
SSH鍵に名前フィールドを追加

### ISSUE THREAD

**Issue by motoki317** [traPtitech/NeoShowcase#781]
UserKeyに名前フィールドを追加して一緒に登録できるように

**Comment by motoki317** [comment]
created_at フィールドもできれば追加したいです 既存レコードは0 (1970/1/1) にでもしとくか
Figmaを参照

**Comment by kyosu-1** [comment]
![image](https://github.com/traPtitech/NeoShowcase/assets/78936861/72507bd8-afca-4a33-9525-776477daf613)

画面memo
