### ISSUE TITLE
削除されたブランチだとフィールドが空で表示される

### ISSUE THREAD

**Issue by motoki317** [traPtitech/NeoShowcase#827]
アプリ設定画面で、ブランチ候補に現在の値が存在しないとフィールドに表示される値が空になってしまう
ブランチが削除された場合に発生する

削除されたブランチなので選択はさせたくないが、空はバグってるように見えるのでよくなさそう

![image](https://github.com/traPtitech/NeoShowcase/assets/18257693/81e0d658-0ff8-4563-abc4-6e205b62d2e7)

**Comment by eyemono-moe** [comment]
https://github.com/traPtitech/NeoShowcase/pull/938 でコンポーネントの修正・整理をした結果、以下のようにpalaceholder(`Select Branch`)が表示されるようになりました。

ブランチ候補に現在の値が存在しない場合以下のようにエラーを表示することもできるのですが、これだとやりすぎでしょうか?

![image](https://github.com/user-attachments/assets/22f31f2f-63c3-42df-9612-c0ee1f82d377)
