### ISSUE TITLE
Commandビルドの場合は.dockerignoreを無視する

### ISSUE THREAD

**Issue by motoki317** [traPtitech/NeoShowcase#877]
現状Dockerfileを生成してビルドする仕組みなので、アプリのリポジトリに `.dockerignore` ファイルがあると、contextをtransferするときにそれに従ってしまう
(Dockerfileビルドの時は.dockerignoreがあれば従うのが正解 solveDockerfile関数を共通で使用しているので注意)

https://github.com/traPtitech/NeoShowcase/blob/510d7cbabf64eb38397ad06abec46076dc25b6e3/pkg/usecase/builder/build_buildkit.go#L130
https://github.com/traPtitech/NeoShowcase/blob/510d7cbabf64eb38397ad06abec46076dc25b6e3/pkg/usecase/builder/build_buildkit.go#L195

Commandビルドの時は、.dockerignoreがあってもその内容はcontext transferの時に無視したい
単純に消してしまうのはユーザーのビルド・結果に影響が出るのでダメ

**Comment by pirosiki197** [comment]
これやろうと思います

buildkitの方に`.dockerignore`を無視するようなオプションがないので
- `.dockerignore`を見つける
  - ないなら通常通り処理する
- `repositoryTempDir`内の`.dockerignore`の名前を適当なものに変える
- `Dockerfile`で`COPY . .`の後に`RUN mv {変更した名前} .dockerignore`を加える
- 後は通常通り

で行こうと思いますがどうでしょう。だいぶ無理やりなので、もっと綺麗な方法があれば教えてほしいです。

**Comment by motoki317** [comment]
workaround的にはそれでもいけそうですね

可能ならば、buildkitやdockerfileのfrontend側に"dockerignoreをignoreする"オプションなんかが無いか見て、もしあればそれを利用したいです
https://github.com/search?q=repo%3Amoby%2Fbuildkit%20dockerignore&type=code
https://github.com/moby/buildkit/blob/08180a774253a8199ebdb629d21cd9f378a14419/frontend/dockerui/namedcontext.go#L213
