### ISSUE TITLE
[Bug]: App > Setting > Build から、Build Type を変更すると1回目だけ表示がおかしくなる

### ISSUE THREAD

**Issue by pikachu0310** [traPtitech/NeoShowcase#899]
### バグの概要

Build Type の表示がバグる

### 再現手順

1. NeoShowcaseの任意のアプリケーションのSettingsを開く
2. Build をクリックし、Build Type を変更する
3. Build Type の詳細設定が開くはずが、なにも表示されない
4. もう一度他のBuild Typeを選択すると治る
5. Build以外の所をクリックしてBuildに戻ったり、リロードすると、再度再現する

### 期待する動作

Build Type の詳細設定が常に表示される

### 実際の動作

Build Type の詳細設定が null (一切表示されない)

### 再現環境

Windows11/Chrome で再現

### スクリーンショット

![image](https://github.com/traPtitech/NeoShowcase/assets/17543997/deed5a48-de8f-4d9a-8316-7ec1d3926458)
![image](https://github.com/traPtitech/NeoShowcase/assets/17543997/5ac90fb9-ef1d-413e-8df5-d5e47eaa8173)

**Comment by eyemono-moe** [comment]
https://github.com/traPtitech/NeoShowcase/issues/902 と同一の原因っぽいのでこちらとまとめて対応予定です
