### ISSUE TITLE
Submit系のボタンを押したらdisabledにする

### ISSUE THREAD

**Issue by motoki317** [traPtitech/NeoShowcase#911]
リクエストが何回も飛んでしまうため

それか何らかのdeduplicationの仕組みをAPIレベルで作る

**Comment by eyemono-moe** [comment]
これmodular formsの`FormStore.submitting`を使ってButtonをdisabledにするようにしているはずなんですが、disabledにできてないformがどっかに存在するというissueですかね?

https://github.com/traPtitech/NeoShowcase/blob/aedfb1a834b8072b0ea83d9b4e1b079e9537a6a0/dashboard/src/pages/apps/%5Bid%5D/settings/general.tsx#L183

**Comment by motoki317** [comment]
少なくともアプリ作成部分でなってないという報告があった

https://q.trap.jp/messages/830c25a6-319a-48a7-be79-1f8a85572d4e
