### ISSUE TITLE
Runtimeアプリのimage sizeをアプリ詳細/ビルド成果ページ等から見たい

### ISSUE THREAD

**Issue by motoki317** [traPtitech/NeoShowcase#921]
どれくらい重いのかの指標になるため

どうやって取ってくるかは要検討
buildkitdのAPIから取れないか？ビルド終了時にregistryから取ってくる？registryにそんな便利なAPIがあるかどうかは分からない harbor APIから取ってくる？
**取得できなくてもサービスの動作には影響が無いようにする**

Staticアプリではartifactとしてそのサイズは表示しているので、それと似た概念となる
UIを設計するときは似た位置や方法・場面で表示したい

**Comment by motoki317** [comment]
buildkitのSolve()で帰って来る情報はこんな感じ

```
&{ExporterResponse:map[containerimage.config.digest:sha256:f89ed71414c8733ce25d886af1abb9e301c80b80c5c80049f8fc2bde7c504051 containerimage.descriptor:eyJtZWRpYVR5cGUiOiJhcHBsaWNhdGlvbi92bmQuZG9ja2VyLmRpc3RyaWJ1dGlvbi5tYW5pZmVzdC52Mitqc29uIiwiZGlnZXN0Ijoic2hhMjU2OmI1MWU0ZDM4NTc5NWM2MTYxMTdmOTI2N2E1NGRmNDM3NTBjNzY5ZTNhZDRjZmU2NDBlZjk0NjgwN2Q1M2U0ZWEiLCJzaXplIjoyMjYyLCJwbGF0Zm9ybSI6eyJhcmNoaXRlY3R1cmUiOiJhbWQ2NCIsIm9zIjoibGludXgifX0= containerimage.digest:sha256:b51e4d385795c616117f9267a54df43750c769e3ad4cfe640ef946807d53e4ea image.name:registry.local/ns-apps/841d190b675e60924f3e7b:f29921cac4b485ba17d45e]}
```

registryから取れるのはcompressed size
https://stackoverflow.com/questions/40377199/how-to-get-total-size-of-a-docker-image-by-docker-api-properly

**Comment by pirosiki197** [comment]
k8sのAPIを利用してNodeにあるImageを取得することを考えたが、
- 取得できる数に制限がありそう
  - https://github.com/kubernetes/kubernetes/issues/93488
- 特定の image size を見ることはできない
  - 全探索するしかない
- `docker images`で見えるサイズと違った(小さめの値が返ってきた)

で難しそう

**Comment by motoki317** [comment]
上PRで既に取得できるようになった

あとは†いい感じ†に表示してほしい
